-- MySQL Script generated by MySQL Workbench
-- sáb 21 mai 2022 18:28:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  `datanascimento` DATE NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `tipousuario` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(60) NOT NULL,
  `numero` VARCHAR(7) NULL,
  `complemento` VARCHAR(20) NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `tipoendereco` VARCHAR(15) NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `preco` DOUBLE NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  `descrição` VARCHAR(60) NOT NULL,
  `imagem` VARCHAR(30) NOT NULL,
  `estoque_minimo` INT(11) NOT NULL,
  `estoque_maximo` INT(11) NOT NULL,
  `qtd_estoque` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itens_pedido` (
  `id` INT UNSIGNED NOT NULL,
  `produto_id` INT NOT NULL,
  `valortotal` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itens_pedidos_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_itens_pedidos_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `mydb`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`forma_pagamento` (
  `idforma_pagamento` INT UNSIGNED NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idforma_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `datacompra` DATE NOT NULL,
  `usuario_id` INT NOT NULL,
  `itens_pedidos_id` INT UNSIGNED NOT NULL,
  `forma_pagamento_idforma_pagamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_pedido_itens_pedidos1_idx` (`itens_pedidos_id` ASC) VISIBLE,
  INDEX `fk_pedido_forma_pagamento1_idx` (`forma_pagamento_idforma_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_itens_pedidos1`
    FOREIGN KEY (`itens_pedidos_id`)
    REFERENCES `mydb`.`itens_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_forma_pagamento1`
    FOREIGN KEY (`forma_pagamento_idforma_pagamento`)
    REFERENCES `mydb`.`forma_pagamento` (`idforma_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrega` (
  `id` INT UNSIGNED NOT NULL,
  `situacao` VARCHAR(45) NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `endereco_id` INT UNSIGNED NOT NULL,
  `pedido_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entrega_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_entrega_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  INDEX `fk_entrega_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
